// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconAbs035: typeof import('./src/components/icons/IconAbs035.vue')['default']
    IconDiscord: typeof import('./src/components/icons/IconDiscord.vue')['default']
    IconFin002: typeof import('./src/components/icons/IconFin002.vue')['default']
    IconGen025: typeof import('./src/components/icons/IconGen025.vue')['default']
    IconSoc006: typeof import('./src/components/icons/IconSoc006.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    NavigationBarItem: typeof import('./src/components/NavigationBar/NavigationBarItem.vue')['default']
    NavigationBarLink: typeof import('./src/components/NavigationBar/NavigationBarLink.vue')['default']
    NavigationBarLogo: typeof import('./src/components/NavigationBar/NavigationBarLogo.vue')['default']
    NavigationBarUser: typeof import('./src/components/NavigationBar/NavigationBarUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
