// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GroupCard: typeof import('./src/components/GroupCard.vue')['default']
    GroupServer: typeof import('./src/components/GroupServer.vue')['default']
    IconAbs035: typeof import('./src/components/Icons/IconAbs035.vue')['default']
    IconArr095: typeof import('./src/components/Icons/IconArr095.vue')['default']
    IconCod001: typeof import('./src/components/Icons/IconCod001.vue')['default']
    IconCom013: typeof import('./src/components/Icons/IconCom013.vue')['default']
    IconDiscord: typeof import('./src/components/Icons/IconDiscord.vue')['default']
    IconFin002: typeof import('./src/components/Icons/IconFin002.vue')['default']
    IconGen0190: typeof import('./src/components/Icons/IconGen0190.vue')['default']
    IconGen0191: typeof import('./src/components/Icons/IconGen0191.vue')['default']
    IconGen025: typeof import('./src/components/Icons/IconGen025.vue')['default']
    IconSoc006: typeof import('./src/components/Icons/IconSoc006.vue')['default']
    IconSoc008: typeof import('./src/components/Icons/IconSoc008.vue')['default']
    MembersGlance: typeof import('./src/components/MembersGlance/MembersGlance.vue')['default']
    MembersGlanceItem: typeof import('./src/components/MembersGlance/MembersGlanceItem.vue')['default']
    MembersGlanceOverflow: typeof import('./src/components/MembersGlance/MembersGlanceOverflow.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    NavigationBarItem: typeof import('./src/components/NavigationBar/NavigationBarItem.vue')['default']
    NavigationBarItemSocial: typeof import('./src/components/NavigationBar/NavigationBarItemSocial.vue')['default']
    NavigationBarLink: typeof import('./src/components/NavigationBar/NavigationBarLink.vue')['default']
    NavigationBarLogo: typeof import('./src/components/NavigationBar/NavigationBarLogo.vue')['default']
    NavigationBarMobile: typeof import('./src/components/NavigationBar/NavigationBarMobile.vue')['default']
    NavigationBarMobileItem: typeof import('./src/components/NavigationBar/NavigationBarMobileItem.vue')['default']
    NavigationBarMobileItemSocial: typeof import('./src/components/NavigationBar/NavigationBarMobileItemSocial.vue')['default']
    NavigationBarUser: typeof import('./src/components/NavigationBar/NavigationBarUser.vue')['default']
    PageHeading: typeof import('./src/components/PageHeading.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
